# Generated by Django 3.1.5 on 2021-01-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
