# Generated by Django 3.1.5 on 2021-01-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_usercartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
