# Generated by Django 3.1.5 on 2021-01-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20210129_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_per_unit',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_total',
        ),
    ]
