# Generated by Django 3.1.5 on 2021-01-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20210129_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipping_address', to='shopping.address'),
        ),
    ]
