# Generated by Django 3.1.5 on 2021-01-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20210129_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
